remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-relative-links
title: JavaScript Cheatsheet
description: Javascript notes focusing on fundamentals and useful interview tips
relative_links:
  enabled: true
  collections: true
